theme: jekyll-theme-slate
markdown: GFM
commithistory: https://github.com/djdallmann/GamingPCSetup/commits/master
ghpageshome: https://djdallmann.github.io/GamingPCSetup/
ghpagesreferences: https://djdallmann.github.io/GamingPCSetup/CONTENT/TECHNICAL%20REFERENCES/
ghpagesresearch: https://djdallmann.github.io/GamingPCSetup/CONTENT/RESEARCH/
